# Generated by Django 3.2.4 on 2023-12-23 11:00

import django.db.models.deletion
from django.db import migrations, models


def initial_filling_db(apss, schema_editor):
    ParcelTypeModel = apss.get_model("core", "ParcelType")

    ParcelTypeModel.objects.bulk_create(
        [ParcelTypeModel(name=name) for name in ("clothes", "electronics", "other")]
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParcelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ParcelType",
                "verbose_name_plural": "ParcelTypes",
            },
        ),
        migrations.CreateModel(
            name="Parcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("weight", models.FloatField(verbose_name="Weight (kg)")),
                ("declared_cost", models.FloatField(verbose_name="Declared cost ($)")),
                (
                    "delivery_cost",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Delivery cost (₽)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("NEW", "NEW"), ("CALCULATED", "CALCULATED")],
                        default="NEW",
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcel",
                        to="core.parceltype",
                        verbose_name="Type",
                    ),
                ),
            ],
            options={"verbose_name": "Parcel", "verbose_name_plural": "Parcels"},
        ),
        migrations.RunPython(initial_filling_db),
    ]
