"""
Django settings for delivery project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

from faker import Faker

BASE_DIR = Path(__file__).parent.parent
ENV = os.environ.get("ENV", "dev")

DEBUG = True
ALLOWED_HOSTS = ["*"]

SECRET_KEY = os.environ.get("SECRET_KEY", Faker().pystr())

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_yasg",
    "apps.core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "delivery.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "delivery.wsgi.application"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation."
        "UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en-US"
TIME_ZONE = "Europe/Moscow"
USE_I18N = True
USE_L10N = True
USE_TZ = True

STATIC_URL = "/static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REDIS_URL = os.environ.get("REDIS_URL", "redis://redis:6379")
BROKER_URL = os.environ.get("CELERY_BROKER", "redis://delivery-redis:6379")
CELERY_RESULT_BACKEND = os.environ.get(
    "CELERY_BROKER_RESULT", "redis://delivery-redis:6379"
)
CELERY_TIMEZONE = "Europe/Moscow"
CELERY_BROKER_TRANSPORT_OPTIONS = {"visibility_timeout": 5 * 60}
CELERY_DEFAULT_QUEUE = os.environ.get("QUEUE_NAME", "delivery")

SWAGGER_SETTINGS = {"LOGIN_URL": "/admin/login/", "LOGOUT_URL": "/admin/logout/"}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("MYSQL_DB", "delivery"),
        "USER": os.environ.get("MYSQL_USER", "mysql_user"),
        "PASSWORD": os.environ.get("MYSQL_ROOT_PASSWORD", "password"),
        "HOST": os.environ.get("MYSQL_HOST", "django_db"),
        "PORT": int(os.environ.get("MYSQL_PORT", 3306)),
        "OPTIONS": {"charset": "utf8mb4"},
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("CACHE_DEFAULT", "redis://delivery-redis:6379/1"),
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    },
    "delivery_tasks_options": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get(
            "CACHE_TASKS_OPTIONS", "redis://delivery-redis:6379/2"
        ),
        "TIMEOUT": 60,
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    },
}
